version: 2.1
executors:
  node:
    docker:
      - image: circleci/node:12-browsers
    working_directory: ~/scaffold
  build-machine:
    docker:
      - image: circleci/node:12
    working_directory: ~/scaffold

  big-machine:
    docker:
      - image: circleci/node:12
    working_directory: ~/scaffold

  super-machine:
    docker:
      - image: circleci/node:10
    working_directory: ~/scaffold

  giant-machine:
    docker:
      - image: circleci/node:12
    working_directory: ~/scaffold

  exec-defaults:
    docker:
      - image: circleci/node:12-browsers
    working_directory: ~/scaffold

jobs:
  build:
    executor: node

    working_directory: ~/scaffold

    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: npm run test:integration
      - run: npx isom tests

  test:
    executor: node

    working_directory: ~/scaffold

    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: npm test

  buildAgain:
    executor: big-machine

    working_directory: ~/scaffold
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: rm -rf node_modules
      - run: rm -r dist
      - checkout
      - run: npm install
      - run: npm run build
      - run: rm -rf node_modules
      - run: rm -r dist
      - checkout
      - run: npm install
      - run: npm run build
      - run: rm -rf node_modules
      - run: rm -r dist
      - checkout
      - run: npm install
      - run: npm run build
      - run: rm -rf node_modules
      - run: rm -r dist
      - checkout
      - run: npm install
      - run: npm run build

  builder:
    executor: super-machine

    working_directory: ~/scaffold
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: rm -rf node_modules
      - run: rm -r dist
      - checkout
      - run: npm install
      - run: npm run build
      - run: rm -rf node_modules
      - run: rm -r dist
      - checkout
      - run: npm install
      - run: npm run build
      - run: rm -rf node_modules
      - run: rm -r dist
      - checkout
      - run: npm install
      - run: npm run build
      - run: rm -rf node_modules
      - run: rm -r dist
      - checkout
      - run: npm install
      - run: npm run build
  worker:
    executor: giant-machine

    working_directory: ~/scaffold
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: rm -rf node_modules
      - run: rm -r dist
      - checkout
      - run: npm install
      - run: npm run build
      - run: rm -rf node_modules
      - run: rm -r dist
      - checkout
      - run: npm install
      - run: npm run build
      - run: rm -rf node_modules
      - run: rm -r dist
      - checkout
      - run: npm install
      - run: npm run build
      - run: rm -rf node_modules
      - run: rm -r dist
      - checkout
      - run: npm install
      - run: npm run build

workflows:
  version: 2
  hourly:
    triggers:
      - schedule:
          cron: "10 * * * *"
          filters:
            branches:
              only:
                - "master"
                - "update"
    jobs:
      - "test"
      - "build"
      - "test"
      - "buildAgain"
      - "builder"
      - "worker"
  weekly:
    triggers:
      - schedule:
          cron: "20 * * * 1,3,5"
          filters:
            branches:
              only:
                - "master"
                - "update"
    jobs:
      - "test"
      - "build"
      - "test"
      - "buildAgain"
      - "builder"
      - "worker"
  nightly:
    triggers:
      - schedule:
          cron: "0 22 * * 1-5"
          filters:
            branches:
              only:
                - "master"
    jobs:
      - "test"
      - "build"
      - "test"
      - "buildAgain"
      - "builder"
      - "worker"
  build:
    jobs:
      - "test"
      - "build"
      - "buildAgain"
      - "builder"
      - "worker"
